"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createHighlighter, type Highlighter } from "shiki/bundle/web";
import {
  getLanguageById,
  type SupportedLanguageId,
  toSupportedLanguageId,
} from "@/lib/code-languages";

interface CodeEditorHighlightProps {
  code: string;
  language: SupportedLanguageId;
  onHighlightReadyChange?: (ready: boolean) => void;
}

const SHIKI_THEME = "github-dark";

let highlighterPromise: Promise<Highlighter> | null = null;

function escapeHtml(code: string) {
  return code
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

async function getHighlighter() {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({
      langs: ["plaintext", "javascript", "typescript", "tsx", "jsx"],
      themes: [SHIKI_THEME],
    });
  }

  return highlighterPromise;
}

void getHighlighter();

export function CodeEditorHighlight({
  code,
  language,
  onHighlightReadyChange,
}: CodeEditorHighlightProps) {
  const [html, setHtml] = useState<string>(() => escapeHtml(code));
  const cacheRef = useRef<Map<string, string>>(new Map());

  const cacheKey = useMemo(
    () => `${SHIKI_THEME}:${language}:${code}`,
    [code, language],
  );

  useEffect(() => {
    let isCurrent = true;

    const cached = cacheRef.current.get(cacheKey);
    if (cached !== undefined) {
      setHtml(cached);
      onHighlightReadyChange?.(true);
      return () => {
        isCurrent = false;
      };
    }

    onHighlightReadyChange?.(false);

    const load = async () => {
      try {
        const highlighter = await getHighlighter();

        const selectedLanguage = getLanguageById(language);
        const shikiLanguage = selectedLanguage?.shiki ?? "plaintext";

        const loadedLanguages = highlighter.getLoadedLanguages();
        if (!loadedLanguages.includes(shikiLanguage)) {
          const loader = selectedLanguage?.shikiLoader;

          if (loader) {
            await highlighter.loadLanguage(loader as never);
          }
        }

        const safeLanguage = toSupportedLanguageId(shikiLanguage);
        const nextHtml = highlighter.codeToHtml(code, {
          lang: getLanguageById(safeLanguage)?.shiki ?? "plaintext",
          rootStyle: false,
          theme: SHIKI_THEME,
        });

        cacheRef.current.set(cacheKey, nextHtml);

        if (isCurrent) {
          setHtml(nextHtml);
          onHighlightReadyChange?.(true);
        }
      } catch {
        if (isCurrent) {
          setHtml(`<pre><code>${escapeHtml(code)}</code></pre>`);
          onHighlightReadyChange?.(true);
        }
      }
    };

    load();

    return () => {
      isCurrent = false;
    };
  }, [cacheKey, code, language, onHighlightReadyChange]);

  return (
    <div
      className="[&_code]:font-mono [&_code]:text-xs [&_code]:leading-5 [&_pre]:m-0 [&_pre]:min-h-full"
      /* biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by Shiki from user code and escaped in fallback. */
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
